# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    - id: black
      name: Black Python code formatting
      entry: bash -c 'black "$@"; git add -u' --
      language: python
      types: [python]
