name: dagger

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dagger
        run: 'pip install dagger-io'

      - name: Test
        run: 'python dagger/test.py' 
